### ISSUE TITLE
Q) shuffle and docom setting

### ISSUE THREAD

**Issue by guyssong** [fanglinpu/JGR-P2O#1]
Hello,  I have a question about shuffle & docom arguments.
Code's all shuffle and docom are set False. 

I want to know the reasons for setting the two arg.

And.. Is the docom option related to refining COM coordinates?

**Comment by fanglinpu** [comment]
The operation of shuffling training data during training is implemented in the "MultiDataStream" interface, please refer to the main_x.py and train function of the model.
We directly use the hand centers from V2V-PoseNet to conduct data preprocessing, so the docom argument is set False.
