### ISSUE TITLE
A conflict between MSRA center point file and Evaluation code

### ISSUE THREAD

**Issue by re20100801** [fanglinpu/JGR-P2O#3]
Dear Author:
       Thank you for sharing your code!
        But during my test, I found there is a conflict between V2V offered MSRA center point file and evaluation code.
        For example, there are 76391 center points in V2V offered MSRA center point but only 76375 Ground Truth in MSRA_2015 datasets.
        Could I know, how do you solve the GAP?
Thank you in advance!
Best Regard.

**Comment by fanglinpu** [comment]
Try to download the updated version of  MSRA in here (https://jimmysuen.github.io./)
